# Settings in the [build] context apply to all Next.js functions and sites
[build]
  # Directory with the exported static files from Next.js
  publish = "out"

  # Command to build the Next.js application
  command = "npm run build"

  # Production settings
  environment = { NODE_ENV = "production" }
