backend:
  name: github
  branch: main
  repo: matthewbdaly/highperformancelaravel.com
publish_mode: editorial_workflow
show_preview_links: false
display_url: https://highperformancelaravel.com/
locale: 'en'
media_folder: "public/img"
public_folder: "img"
collections:
  - name: pages
    label: "Pages"
    label_singular: "Page"
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "{{slug}}"
    show_preview_links: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
    sortableFields: ["title", "description", "body"]
    summary: "{{title}} - {{commit_author}}"
  - name: "series" # Used in routes, e.g., /admin/collections/blog
    label: "Series" # Used in the UI
    label_singular: "Series"
    folder: "content/series" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{series}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "tutorials/series/{{series}}"
    show_preview_links: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured image", name: "featured_image", widget: "image"}
      - {label: "Featured image username", name: "featured_image_username", widget: "string"}
    sortableFields: ["date", "title", "description", "body"]
    summary: "{{title}} - {{commit_author}}"
  - name: "tutorials" # Used in routes, e.g., /admin/collections/blog
    label: "Tutorials" # Used in the UI
    label_singular: "Tutorial"
    folder: "content/tutorials" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "tutorials/series/{{series}}/{{slug}}"
    show_preview_links: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Series", name: "series", widget: "list", required: false, allow_add: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured image", name: "featured_image", widget: "image"}
      - {label: "Featured image username", name: "featured_image_username", widget: "string"}
    sortableFields: ["date", "title", "description", "body", "series"]
    summary: "{{title}} - {{commit_author}}"
